# Default configuration for vehicle detector
model: yolov8n.pt
confidence: 0.25
max_fps: 30           # Cap processing to this FPS (after stride). Set 0 to disable
stride_frames: 2      # Sample every Nth frame (>=1). Lower for more aggressive sampling.
iou: 0.5
device: auto          # 'auto', 'cpu', 'cuda', or index like 0
imgsz: 640            # YOLO inference image size
classes: [2]      # COCO: car(2), bus(5), truck(7). Excludes motorcycle by default
batch_size: 8
tracking:
  # Increased to tolerate longer detection gaps (~2s at 30 processed FPS)
  max_age: 60
  # Require two consecutive hits before confirming a track to avoid spurious IDs
  n_init: 2
  # Slightly relaxed to help re-associate after motion/scale changes
  max_iou_distance: 0.8
  # Slightly relaxed to rely more on appearance for continuity
  max_cosine_distance: 0.3
  nn_budget: 100
color_filter:
  mode: hsv
  white_ratio_threshold: 0.25
  enabled: true
  # Optional: exclude clearly colored vehicles even if they have strong specular highlights
  hue_veto:
    enabled: true
    fraction: 0.2       # if >= 20% of pixels are strongly colored in the bands below, reject as non-white
    s_min: 80           # saturation threshold to consider a pixel strongly colored
    v_min: 80           # value threshold to avoid dark noise
    # Default hue bands: red (two ranges to wrap around), blue
    bands:
      - [0, 10]
      - [170, 179]
      - [100, 140]
  # Pearl white range in Lab space; tweak as needed
  lab:
    L_min: 70
    L_max: 100
    a_min: -5
    a_max: 8
    b_min: -5
    b_max: 15
  min_box_area: 1000     # Skip tiny boxes
  erosion: 1
sedan_only: false        # If true, use heuristic shape ratio filter; proper classifier not bundled
segment_export:
  pre_seconds: 5
  post_seconds: 5
  codec: libx264
  crf: 23
  preset: veryfast
  reencode: false   # If false, tries stream copy; falls back to reencode if not possible
stills:
  enabled: true           # Export one representative still frame per matching track
  annotate: true          # Draw bbox and track id on the still frame
  save_crop: false        # Also save a cropped vehicle image
  edge_margin: 8          # Pixels from edge considered incomplete
  out_dirname: stills     # Subdirectory name for stills
  global_dir: all_stills
  # Ordering and naming options for easier chronological review
  sort_by_frame: true           # Save/export stills sorted by frame index (chronological)
  filename_prefix_frame: true   # Prefix filenames with frame index so name-sort is chronological
  write_index_csv: true         # Write a stills_index.csv sorted by frame
reid_filter:
  enabled: false                 # When true, copy high-confidence stills into a separate folder
  gallery_dir: ""               # Path to your target gallery images (5-10 best views)
  threshold: 0.88                # Cosine similarity threshold to consider a match
  arch: osnet_x1_0               # Backbone arch for embeddings; falls back to resnet50 if TorchReID missing
  weights: ""                   # Optional path to trained weights matching arch
  size: 256
  batch: 64
  device: auto                  # 'cuda', 'cpu', or 'auto'
  out_dirname: reid_high_conf   # Subfolder under video output to copy high-confidence stills
  global_dir: all_reid_high     # Optional flat global folder under output to aggregate matches
